language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t eppifoss/eureka -f Dockerfile.dev   . 

script:
  - docker run  -e CI=true eppifoss/eureka npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "eureka"
  env: "eureka-env"
  bucket_name: "elasticbeanstalk-us-west-2-476578251364"
  bucket_path: "eureka"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
